#!/command/with-contenv bash

OT_LOG_LEVEL="${OT_LOG_LEVEL:-7}"
readonly OT_LOG_LEVEL

OT_THREAD_IF="${OT_THREAD_IF:-wlan0}"
readonly OT_THREAD_IF

OT_WEB_LISTEN_ADDR="${OT_WEB_LISTEN_ADDR:-127.0.0.1}"
readonly OT_WEB_LISTEN_ADDR

OT_WEB_LISTEN_PORT="${OT_WEB_LISTEN_PORT:-80}"
readonly OT_WEB_LISTEN_PORT

echo "Starting otbr-web..."

exec /usr/sbin/otbr-web \
        -a "${OT_WEB_LISTEN_ADDR}" \
        -p "${OT_WEB_LISTEN_PORT}" \
        -I "${OT_THREAD_IF}" \
        -d "${OT_LOG_LEVEL}"
