FROM docker.io/caddy:2.10.2-builder-alpine AS builder

RUN xcaddy build \
  --with github.com/caddy-dns/cloudflare \
  --with github.com/mholt/caddy-l4

# Prepare S6 overlay source
RUN apk add curl ca-certificates

ENV S6_OVERLAY_VERSION=3.2.1.0
ARG TARGETARCH
ARG TARGETVARIANT

RUN mkdir /install
RUN PLATFORM_SPEC="${TARGETARCH}${TARGETVARIANT:+/$TARGETVARIANT}" \
    && case "${PLATFORM_SPEC}" in \
         "amd64") S6_ARCH="x86_64" ;; \
         "arm/v7") S6_ARCH="arm" ;; \
         "arm/v6") S6_ARCH="armhf" ;; \
         "arm64") S6_ARCH="aarch64" ;; \
         *) echo "Unsupported architecture: ${PLATFORM_SPEC}"; exit 1 ;; \
       esac \
    && curl -L -f -s "https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz" \
        | tar Jxvf - -C /install \
    && curl -L -f -s "https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-${S6_ARCH}.tar.xz" \
        | tar Jxvf - -C /install

FROM docker.io/alpine:3.23.0

RUN apk add --no-cache ifupdown-ng socat openssh

RUN ssh-keygen -A

COPY --from=builder /install /
# Also make s6 init in regular init location, so systemd-nspawn can find and
# boot
COPY --from=builder /install/init /sbin/init
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
COPY rootfs /

ENTRYPOINT ["/init"]
